//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManikurSalon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManikurSalonEntities : DbContext
    {
        private static ManikurSalonEntities entities;
        public ManikurSalonEntities()
            : base("name=ManikurSalonEntities")
        {
        }
        
        public static ManikurSalonEntities GetContext()
        {
            if (entities == null)
                entities = new ManikurSalonEntities();
            return entities;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorya> Categorya { get; set; }
        public virtual DbSet<Masters> Masters { get; set; }
        public virtual DbSet<Stud> Stud { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Yslyga> Yslyga { get; set; }
        public virtual DbSet<Zapis> Zapis { get; set; }
    }
}
