//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManikurSalon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yslyga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yslyga()
        {
            this.Zapis = new HashSet<Zapis>();
        }
    
        public int ID_Yslyga { get; set; }
        public int ID_Categorya { get; set; }
        public string NazvanieYslygi { get; set; }
        public int Price { get; set; }
    
        public virtual Categorya Categorya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zapis> Zapis { get; set; }
    }
}
