//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManikurSalon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapis
    {
        public int ID_Zapis { get; set; }
        public int ID_stud { get; set; }
        public int ID_Yslyga { get; set; }
        public string Time { get; set; }
        public int ID_Master { get; set; }
        public string Name_Zakasik { get; set; }
        public string SecondName_Zakasik { get; set; }
        public string Otchestvo_Zakasik { get; set; }
    
        public virtual Masters Masters { get; set; }
        public virtual Stud Stud { get; set; }
        public virtual Yslyga Yslyga { get; set; }
    }
}
